var panelElement = document.createElement('div');
panelElement.innerHTML = panelHTML;
document.getElementsByTagName('body')[0].appendChild(panelElement);
var wikiPageFooter = document.querySelector("div#footer");
wikiPageFooter.className += " addPaddingForPage";

var script = document.createElement('script');
script.setAttribute("type", "application/javascript");
script.textContent = "function showDiff(diffText) { debugger; var myWindow = window.open('', 'MsgWindow', 'width=1000, height=1000'); myWindow.document.write(\"<html><head><style type='text/css'>table.diff{border:none;border-spacing:4px;margin:0;width:100%;table-layout:fixed}table.diff td{padding:0.33em 0.5em}table.diff td.diff-marker{padding:0.25em}table.diff col.diff-marker{width:2%}table.diff col.diff-content{width:48%}table.diff td div{word-wrap:break-word}td.diff-otitle,td.diff-ntitle{text-align:center}td.diff-lineno{font-weight:bold}td.diff-marker{text-align:right;font-weight:bold;font-size:1.25em;line-height:1.2}td.diff-addedline,td.diff-deletedline,td.diff-context{font-size:88%;line-height:1.6;vertical-align:top;white-space:-moz-pre-wrap;white-space:pre-wrap;border-style:solid;border-width:1px 1px 1px 4px;border-radius:0.33em}td.diff-addedline{border-color:#a3d3ff}td.diff-deletedline{border-color:#ffe49c}td.diff-context{background:#f9f9f9;border-color:#e6e6e6;color:#333333}.diffchange{font-weight:bold;text-decoration:none}td.diff-addedline .diffchange,td.diff-deletedline .diffchange{border-radius:0.33em;padding:0.25em 0}td.diff-addedline .diffchange{background:#d8ecff}td.diff-deletedline .diffchange{background:#feeec8}@media print{td.diff-context,td.diff-addedline .diffchange,td.diff-deletedline .diffchange{background-color:transparent}td.diff-addedline .diffchange{text-decoration:underline}td.diff-deletedline .diffchange{text-decoration:line-through}}</style></head><body>\" + \"</body></html>\"); myWindow.document.body.appendChild(diffText); } function getDiffTable(responseHTML) { var dummyDiv = document.createElement('div'); dummyDiv.innerHTML = responseHTML; var tableAry = dummyDiv.getElementsByClassName('diff diff-contentalign-left'); showDiff(tableAry[0]); } \n var getPageContent = function(url) { \n var req = new XMLHttpRequest(); \n req.open('GET', url, true); \n req.onreadystatechange = function(aEvt) { \n if (req.readyState == 4) { \n if (req.status == 200) { \n getDiffTable(req.responseText); \n } \n } \n } \n req.send(null); \n  }; \n function getDiffText(divName) { \n var url = document.getElementById(divName).innerHTML.replace(/amp;/g, ''); \n console.log(url); \n getPageContent(url); \n } function closePane() { var elem = document.getElementById('panel'); elem.parentNode.removeChild(elem); var wikiPageFooter = document.querySelector('div#footer'); wikiPageFooter.className = wikiPageFooter.className.replace(' addPaddingForPage', ''); } function makeHTMLRequest(url) { var request = new XMLHttpRequest(); request.open('GET', url, false); request.send(null); return request.responseText; } ";
document.body.appendChild(script);